### ISSUE TITLE
No way to open device with two endpoints

### ISSUE THREAD

**Issue by moyix** [trezor/cython-hidapi#10]
I'm working with a Fitbit dongle, which exposes two HID endpoints (one for control, one for data). The information from hid.enumerate(VID,PID) doesn't give any way to distinguish between the two devices:

    In [4]: hid.enumerate(VID, PID)
    Out[4]: 
    [{'interface_number': -1,
      'manufacturer_string': u'Fitbit Inc.',
      'path': 'USB_2687_fb01_14500000',
      'product_id': 64257,
      'product_string': u'Fitbit Base Station',
      'release_number': 256,
      'serial_number': u'\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff',
      'usage': 1,
      'usage_page': 65290,
      'vendor_id': 9863},
     {'interface_number': -1,
      'manufacturer_string': u'Fitbit Inc.',
      'path': 'USB_2687_fb01_14500000',
      'product_id': 64257,
      'product_string': u'Fitbit Base Station',
      'release_number': 256,
      'serial_number': u'\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff',
      'usage': 1,
      'usage_page': 65290,
      'vendor_id': 9863}]

So using `dev.open(vid, pid)` or `dev.open_path(path)` doesn't give me any way to open the second device, since the information is identical.

Is there any way to do this?

**Comment by prusnak** [comment]
You did not write which OS you are using so I am going to assume it's OS X which exhibits this behaviour. Sadly this is a limitation of OS X which has to be circumvented in hidapi itself. See https://github.com/signal11/hidapi/issues/193 ... Closing as this is not a cython-hidapi issue.
