### ISSUE TITLE
Memory leak in `get_feature_report`/`get_input_report`/`read`

### ISSUE THREAD

**Issue by Youw** [trezor/cython-hidapi#101]
Each of: `get_feature_report`/`get_input_report`/`read` implements a buffer optimisation - use static/on stack buffer of 16 elements for read, and allocates larger buffer with `malloc`, of larger buffer is required.

The problem is that `free` is [called](https://github.com/trezor/cython-hidapi/blob/6539756c42cddf63cfee3eb40f5e570c0cb9d1ec/hid.pyx#L129) after a potential [exception](https://github.com/trezor/cython-hidapi/blob/6539756c42cddf63cfee3eb40f5e570c0cb9d1ec/hid.pyx#L124).

Classic :)

Please excuse me for not finding time for a PR with the fix, at least letting the community aware of the problem.

**Comment by prusnak** [comment]
> Classic :)

Your suggestion is to call `free(cbuff)` before `raise`, right?

**Comment by Youw** [comment]
if python guarantees, that `append` doesn't raise any exceptions (even unlikely ones), that would suffice
but I think more general approach is to move `free` into the `final` block (same way is `open` does it)

**Comment by prusnak** [comment]
@Youw I created PR https://github.com/trezor/cython-hidapi/pull/102 - can you please have a look if that's what you've imagined? Thanks!

**Comment by Youw** [comment]
As far as I can tell - looks good!
