### ISSUE TITLE
Release windows wheels for 3.8 in 0.7.99.post21

### ISSUE THREAD

**Issue by k9ert** [trezor/cython-hidapi#103]
Hi, very much appreciating your work. Over at [specter-desktop](https://github.com/cryptoadvance/specter-desktop) we're a bit in a tricky situation with https://github.com/cryptoadvance/specter-desktop/issues/830 . We're having trouble building hidapi version 0.7.99.post21 on python 3.8 on the windows platform.
Roughly, we think we have three options:

>    * We either need VisualStudio to build from hidapi-source-package on windows or
>     * The old version 0.7.99.post21 need to provide a wheel-package for windows out of the box or
>     * HWI is upgrading hidapi

Andrew Chow jumped in but couldn't give us a reasonable timeline when HWI is upgrading to a newer version. Can you help us out with providing wheels for for 3.8 in 0.7.99.post21 or maybe suggest something different?

**Comment by prusnak** [comment]
Why don't you use 0.10.1 from PyPI which also contains Wheels for windows?

https://pypi.org/project/hidapi/

**Comment by k9ert** [comment]
We're not directly using it but via HWI and it's already in but not for 1.x but 2.x. But there is no 2.x release yet. So that's why we asked @achow101 and his answer was:

> I cannot give a timeline for when the next release will be made. The current plan is to make a 2.0 release which addresses 
> several existing issues but also breaks some of the API.

**Comment by prusnak** [comment]
I managed to build 3.8 Windows wheels via AppVeyor - https://pypi.org/project/hidapi/0.7.99.post21/#files

Hope that helps!

**Comment by k9ert** [comment]
Awesome! Thank you, very much appreciated!
