### ISSUE TITLE
Add tests via GitHub actions

### ISSUE THREAD

**Issue by prusnak** [trezor/cython-hidapi#104]
We used to have Travis, but since it's removed now we should re-add the following tests via GitHub Actions: https://github.com/trezor/cython-hidapi/blob/b16f093b47edaaf1362d2fdcc3584d8633431342/.travis.yml

**Comment by mcuee** [comment]
Maybe something similar to pyusb by @jonasmalacofilho 
https://github.com/pyusb/pyusb/blob/master/.github/workflows/run_tox.yml
