### ISSUE TITLE
Linux wheels try to access undefined HIDIOCGFEATURE symbol

### ISSUE THREAD

**Issue by jonasmalacofilho** [trezor/cython-hidapi#105]
I just had this failure in CI, and haven't had time to investigate it fully yet.  Will update along the way...

Still, the new Linux wheels appear to have been compiled in a way that breaks the hidraw module, at least in a vanilla-ish Ubuntu environment (GitHub Actions `ubuntu-latest`).

```
     import hidraw as hid
E   ImportError: /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/hidraw.cpython-37m-x86_64-linux-gnu.so: undefined symbol: HIDIOCGFEATURE
```

The same failure was noticed with Python 3.8 and, presumably, it should also affect Python 3.9.

[Complete log output of the failed GH Action](https://github.com/liquidctl/liquidctl/actions/runs/501540002)

**Comment by prusnak** [comment]
I guess we need to use older ubuntu release than latest in the Github CI

**Comment by jonasmalacofilho** [comment]
That was one of my first thoughts.  But I can reproduce it on a fresh venv on Arch, which means that it's less likely to be as simple as 'build it with older libs."

```
$ cd /tmp
$ python -m venv venv
$ source venv/bin/activate
$ pip install hidapi
Collecting hidapi
  Downloading hidapi-0.10.1-cp39-cp39-manylinux2010_x86_64.whl (422 kB)
     |████████████████████████████████| 422 kB 7.3 MB/s 
Requirement already satisfied: setuptools>=19.0 in ./venv/lib/python3.9/site-packages (from hidapi) (49.2.1)
Installing collected packages: hidapi
Successfully installed hidapi-0.10.1
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the '/tmp/venv/bin/python -m pip install --upgrade pip' command.
$ python -c "import hidraw"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /tmp/venv/lib/python3.9/site-packages/hidraw.cpython-39-x86_64-linux-gnu.so: undefined symbol: HIDIOCGFEATURE
```

Any chance the uploaded wheels were built with experimental cython-hidapi or hidapi code?

**Comment by jonasmalacofilho** [comment]
`ldd` doesn't show anything obviously wrong but it's interesting (and perhaps problematic) that the wheel links to a custom libudev so.

```
$ ldd /tmp/venv/lib/python3.9/site-packages/hidraw.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fffc79e5000)
	libudev-20d87ef6.so.0.5.1 => /tmp/venv/lib/python3.9/site-packages/hidapi.libs/libudev-20d87ef6.so.0.5.1 (0x00007f8758d39000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f8758ce6000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8758cc4000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f8758afb000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f8759162000)
```

**Comment by jonasmalacofilho** [comment]
Possibly related: http://lkml.iu.edu/hypermail/linux/kernel/1104.1/00315.html

> On systems where userspace doesn't have new hidraw.h populated to
/usr/include, the hidraw sample won't compile as it's missing the new
ioctl defitions.

For reference, building hidapi on my system would find the `HIDIOCGFEATURE` definition in:

```
$ grep -rn HIDIOCGFEATURE /usr/include
/usr/include/linux/hidraw.h:41:#define HIDIOCGFEATURE(len)    _IOC(_IOC_WRITE|_IOC_READ, 'H', 0x07, len)
```

**Comment by prusnak** [comment]
It seems we need to install linux kernel headers - trying this in 94629c9465b6727b53922e61fb9de0c2aeca5143

**Comment by jonasmalacofilho** [comment]
Tried the generated artifact but the issue still appears to be there:

```
# reset the test venv
$ pip install hidapi-0.10.1-cp39-cp39-manylinux2010_x86_64.whl
Processing ./hidapi-0.10.1-cp39-cp39-manylinux2010_x86_64.whl
Requirement already satisfied: setuptools>=19.0 in ./venv/lib/python3.9/site-packages (from hidapi==0.10.1) (49.2.1)
Installing collected packages: hidapi
Successfully installed hidapi-0.10.1
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the '/tmp/venv/bin/python -m pip install --upgrade pip' command.
$ python -c "import hidraw"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /tmp/venv/lib/python3.9/site-packages/hidraw.cpython-39-x86_64-linux-gnu.so: undefined symbol: HIDIOCGFEATURE
```

**Comment by prusnak** [comment]
Replaced `kernel-devel` with `kernel-headers` in 27da2008b99db847c09000382ed8caf2fb46278c

Can you please test if that worked for you?

**Comment by prusnak** [comment]
Hm, seems that kernel-headers are install by default:

```
  Package kernel-headers-2.6.32-754.35.1.el6.x86_64 already installed and latest version
74
```

but the kernel version seems to be really really old.

I might switch to manylinux2014

**Comment by prusnak** [comment]
Pushed manylinux2014 change to manylinux2014 branch - Wheel action running in the CI

**Comment by jonasmalacofilho** [comment]
> but the kernel version seems to be really really old.
> Pushed manylinux2014 change to manylinux2014 branch - Wheel action running in the CI

I'm glad to confirm that 4739f827194d (manylinux2014) solves it on my local repro.  Should work just as well in CI, though the increased minimum required `pip` version is a small concern when thinking about users running very old distros...

**Comment by prusnak** [comment]
Thanks for the confirmation. I nuked the non-functional manylinux2010 wheels and uploaded the working manylinux 2014 ones to PyPI: https://pypi.org/project/hidapi/#files

**Comment by jonasmalacofilho** [comment]
CI is also working with the new wheels.

Thanks again!
