### ISSUE TITLE
Basic documentation (ReadTheDocs)

### ISSUE THREAD

**Issue by RobertoRoos** [trezor/cython-hidapi#106]
Would it be worthwhile to start documentation of some of the basics?
A [readthedocs.org](readthedocs.org) project based on a simple Sphinx build would be nice.

I'm not sure if Sphinx's `autodoc` would work with a C-based library, but worth a try.

I might make an example soon.

**Comment by markspan** [comment]
It’s the feature I’ve been missing most from this lib…… m.Sent from Mail for Windows 10 From: RobertSent: Tuesday, 9 February 2021 09:26To: trezor/cython-hidapiCc: SubscribedSubject: [trezor/cython-hidapi] Basic documentation (ReadTheDocs) (#106) Would it be worthwhile to start documentation of some of the basics?A readthedocs.org project based on a simple Sphinx build would be nice.I'm not sure if Sphinx's autodoc would work with a C-based library, but worth a try.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by prusnak** [comment]
Pull requests are welcome. 

Upstream library (hidapi) uses Doxygen for documentation - https://github.com/libusb/hidapi - so maybe we could just link our repo to their documentation? This wrapper library does nothing extra except for calling the C code underneath.

**Comment by RobertoRoos** [comment]
Right.

The problem is the interfaces are not identical. But we could chain a doxygen build of the underlying library with our Sphinx project and link it where relevant.

I've created a minimal set-up with autodoc and a few members have some documentation:
![image](https://user-images.githubusercontent.com/12717020/107349318-5c54d900-6ac8-11eb-81e5-f6eb76fd1bb6.png)

The frustrating part is I have no idea where these docs come from and how I could change or add to them.

**Comment by prusnak** [comment]
Yes, `hid.pyx` and `chid.pxd` are not autogenerated and are manually written. All other files are autogenerated or reused from upstream without any changes.

**Comment by RobertoRoos** [comment]
Hm, I have most of it figured it out. Fork: https://github.com/RobertoRoos/cython-hidapi
And RTD project: https://readthedocs.org/projects/roberto-hidapi

But the hidapi library is not being built by RTD, build log: https://readthedocs.org/projects/roberto-hidapi/builds/12974725/
Two dependencies are missing (libusb and libudev), and RTD doesn't provide apt installs. Need to figure this out.

**Comment by RobertoRoos** [comment]
Tried a new approach based on a conda environment (which is supposed to make c-library management easier): https://github.com/RobertoRoos/cython-hidapi/tree/feature/docsconda

But it's still failing with errors I cannot reproduce: https://readthedocs.org/projects/roberto-hidapi/builds/12977506/

Maybe we should settle for a static host instead? Maybe with Github pages?

**Comment by prusnak** [comment]
> Maybe we should settle for a static host instead? Maybe with Github pages?

Could be - just generate the docs into the `docs/` folder, send PR to `master` and I'll publish it as GitHub pages.

**Comment by RobertoRoos** [comment]
Pull request has been opened.
I kind of dislike the idea of committing the generated docs. Instead I created an export here: 
[cython-hidapi-docs.zip](https://github.com/trezor/cython-hidapi/files/5956446/cython-hidapi-docs.zip)

**Comment by prusnak** [comment]
Thank you! I deployed the documentation to https://trezor.github.io/cython-hidapi/
