### ISSUE TITLE
 please consider using a standard license

### ISSUE THREAD

**Issue by ulrichard** [trezor/cython-hidapi#11]
I'm in the process of packaging your library for debian. Now there came up an issue with the license. It is short and simple, and the intention seems clear, but there might be some ambiguities. As debian is very strict with licenses, it would be helpful, if you could adopt one of the standard licenses. The Expat / MIT license would probably be the closest to what you currently have.
I logged the issue also against the original at : https://github.com/gbishop/cython-hidapi/issues/19. But you would both have to agree to a license change.

**Comment by prusnak** [comment]
I think it's enough to track this issue only once (in upstream), where I explained my opinion. If there is no answer there, we can reopen the discussion here.

**Comment by ulrichard** [comment]
Please merge the new license from https://github.com/gbishop/cython-hidapi
It would be nice if you created a new release with that. So I can use it for the debian package.

**Comment by prusnak** [comment]
Fixed in b7767152e63000536967f97a26af78442755bbac

**Comment by prusnak** [comment]
Uploaded as https://pypi.python.org/pypi/hidapi/0.7.99-6

**Comment by ulrichard** [comment]
Thanks a lot
