### ISSUE TITLE
.read immediately after .write

### ISSUE THREAD

**Issue by dphaas** [trezor/cython-hidapi#113]
I have a simple write, delay, read sequence:
        self.mcp2221a.write(buf)
        time.sleep(1)
        rbuf = self.mcp2221a.read(PACKET_SIZE)
The hardware I'm communicating with needs the delay to accomplish a task but I keep getting command completion error.  What I see on Wireshark is the read immediately follows, within 1 ms, the write which does not allow the command to complete.  It's as if hidapi anticipates the USB read and executes prior to the Python statement.
Wireshark capture:
![image](https://user-images.githubusercontent.com/13985782/109730145-3de97700-7b76-11eb-9f5a-b2bcf003fad8.png)

**Comment by dphaas** [comment]
Same behavior is observed when single stepping in debug.  Read is seen on USB bus prior to Python statement execution and when Python statement is executed on USB transaction is observed.

**Comment by jonasmalacofilho** [comment]
What's probably going on is that the kernel has to automatically enqueue incoming HID reports, which means it's always reading from the device, at the device's specified pooling rate.

You may be able to override this behavior at the kernel level (either by disabling this queue or by changing the pooling rate), but maybe the device shouldn't present itself as a HID if it doesn't expect to be used according to the HID specification.

**Comment by prusnak** [comment]
Like said above, this seems like the issue of a hardware you are using, not the library. 

What kind of device are you using? Is that some kind of DIY device? If yes and refreshing every 1 ms is not what you want, you should increase the polling interval in the USB endpoint descriptor. See `bInterval` in https://www.beyondlogic.org/usbnutshell/usb5.shtml#EndpointDescriptors

**Comment by dphaas** [comment]
Hey Guys thanks for the prompt responses.  You guys are absolutely right.  After digging in to HID descriptions (thanks for the link) and underlying USB interrupt functions it is clear the system side, including the library, is doing everything it should with very little latency.  Sorry to bother you!

As background, I am trying to get https://github.com/nonNoise/PyMCP2221A to work with a PICKit serial adaptor (Microchip MCP2221A) connected to PMBus power supply.  This involves USB HID > I2C Bus > SMBus > PMBus.  PyMCP2221A  has some "may want to add sleep() time" comments, so obviously there has been some issues that have not been resolved.  hipapi library is not the cause.

**Comment by jonasmalacofilho** [comment]
I'm curious, is this power supply with a PIC-based bridge to PMBus an off-the-shelve product?

**Comment by dphaas** [comment]
The power supply is Advanced Energy Coolx600 with PMBus (slave).  The PMBus master is a PICKit Serial (MCP2221A).
![PMBus](https://user-images.githubusercontent.com/13985782/110017257-414e4100-7ce3-11eb-8381-c090f1d13286.jpg)

**Comment by jonasmalacofilho** [comment]
Cool!  And thanks for humoring my curiosity : )
