### ISSUE TITLE
Windows installation privileges issue

### ISSUE THREAD

**Issue by simonsolnes** [trezor/cython-hidapi#115]
I'm running PowerShell as administrator.
On command `python setup.py install` I get:

```
[Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-3436.write-test'
```

**Comment by prusnak** [comment]
This does not seem related to cython-hidapi and I am not able to provide troubleshooting for Windows Python installations.

**Comment by mcuee** [comment]
Suggestion: do not use the Windows Store version. It seems to have various problems. Rather use the nomal Python.org version.
