### ISSUE TITLE
Expose hid_device->device_handle

### ISSUE THREAD

**Issue by Adminiuga** [trezor/cython-hidapi#117]
Would it be possible to expose hidapi's  `hid_device->device_handle` to python environment? `pyserial` hass support for CP2110 Silicon Labs UART bridge, however it is not possible to use it with `pyserial-asyncio`, because the serial device cannot expose the file descriptor of the HID device, resulting in the errors like

```
(dev) lex@deb:~/lex/src$ bellows -v debug -b 115200 -d cp2110://0002:0005:00 info
debug: Using selector: EpollSelector
debug: Using selector: EpollSelector
Connecting to cp2110://0002:0005:00
Exception in callback SerialTransport._ensure_reader()
handle: <Handle SerialTransport._ensure_reader()>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/lex/.venv/dev/lib/python3.9/site-packages/serial_asyncio/__init__.py", line 319, in _ensure_reader
    self._loop.add_reader(self._serial.fileno(), self._read_ready)
io.UnsupportedOperation: fileno
```

**Comment by prusnak** [comment]
It seems like this is a missing feature of `pyserial` or bug in `pyserial-asyncio`, rather than a missing feature of `cython-hidapi`.

**Comment by Adminiuga** [comment]
I was looking into adding it to pyserial, but came to conclusion that it would not be possible without `hidapi` exposing the file descriptor. `pyserial` is using `hidapi` package for communication with the USB UART bridge, but for the asyncio one to work, the `pyserial` needs to know to the underlyiung file descriptor of the opened hidapi device. 

Or in case I missing anything, how in the following code would you get the device_handle of the opened device?

```
import hid
dev = hid.device()
dev.open("0002:0004:00")
```

Once I have access to FD, then the pyserial change is trivial.

**Comment by prusnak** [comment]
I missed the fact that `pyserial` is using `hidapi` as its dependency (for `cp2110`), sorry.

It seems that `hid_device->device_handle` is a hidapi backend specific structure and not a file descriptor like you assume.

**Comment by Adminiuga** [comment]
First, I'd like to thank you for taking your time to look into this issue. But can you bear with me a tad longer please :) I'm new to Cython and might not know exactly what i'm looking at at, nor how to do it.

Do I understand correctly that [device.open_path()](https://github.com/trezor/cython-hidapi/blob/b94c8a09582681aff6edd145a3bfd3948ff7e5ca/hid.pyx#L123) method calls the hidapi's backend [hid_open_path()](https://github.com/libusb/hidapi/blob/f6d0073fcddbdda24549199445e844971d3c9cef/hidapi/hidapi.h#L216) which returns a `hid_device` structure and we keep it as a private instance attribute of the device? 

This hid device structure [here](https://github.com/libusb/hidapi/blob/f6d0073fcddbdda24549199445e844971d3c9cef/linux/hid.c#L65) has the `device_handle` which I assume is the file handle, because I see it being used as an argument of the `fstat()` function [here](https://github.com/libusb/hidapi/blob/f6d0073fcddbdda24549199445e844971d3c9cef/linux/hid.c#L485) so I assumed this is the file descriptor I was looking for.  To test this hypothesis, can you help me expose the device_handle and I'll test is further?

**Comment by Adminiuga** [comment]
actually here https://github.com/libusb/hidapi/blob/f6d0073fcddbdda24549199445e844971d3c9cef/linux/hid.c#L905 the device_handle is the file descriptor, isn't it?

**Comment by prusnak** [comment]
> actually here https://github.com/libusb/hidapi/blob/f6d0073fcddbdda24549199445e844971d3c9cef/linux/hid.c#L905 the device_handle is the file descriptor, isn't it?

Yes, but if you use linux/libusb backend it is a libusb structure, on macos it is IOHIDDeviceRef and on windows it is HANDLE, see:
* https://github.com/libusb/hidapi/blob/f6d0073fcddbdda24549199445e844971d3c9cef/windows/hid.c#L144
* https://github.com/libusb/hidapi/blob/f6d0073fcddbdda24549199445e844971d3c9cef/mac/hid.c#L112
* https://github.com/libusb/hidapi/blob/f6d0073fcddbdda24549199445e844971d3c9cef/libusb/hid.c#L147

Exposing internal value which has semantics depending on underlying backend does not sound great.

We could support only native hid backend on linux and nothing else (not even libusb on linux), but I am not sure this helps.

**Comment by Adminiuga** [comment]
Got it. Thanks for the explanation. Yeah, I agree on the above.
