### ISSUE TITLE
Read - returns list of ints, need byte array

### ISSUE THREAD

**Issue by drmcnelson** [trezor/cython-hidapi#118]
The api  read() returns a list of int.   We need bytearray.

The list of int, first of all, is not what was sent.   Second,  it is awkward to work with and waste cycles to convert back to the original or another representation that we had in mind when we programmed the device that sends the data.

**Comment by prusnak** [comment]
We can't break the API because there are lots of projects depending on it.

Just convert it to bytes or bytearray as you wish - the conversion is trivial.

**Comment by drmcnelson** [comment]
Can you suggest a python code to do that conversion efficiently?

How about adding another call,   read_bytearray()

**Comment by prusnak** [comment]
```
res = foo.read()
```

then

```
b = bytearray(res)
```

or

```
b = bytes(res)
```
