### ISSUE TITLE
ModuleNotFoundError: No module named 'hidapi' after install

### ISSUE THREAD

**Issue by CloudyChris** [trezor/cython-hidapi#119]
Garuda Linux ( Arch based ) with linkux-tkg,
tried both the pip install and the arch repos pyhton-hidapi
hidraw is installed as hidapi ( from arch repos ) and confirmed that works in C.
tried both for user scope and system scope ( with sudo ),
tried with an env ( conda )
it just won't work...

Any ideas?

**Comment by prusnak** [comment]
No idea. Please ask your distribution maintainers.
