### ISSUE TITLE
Send Feature Report not working on Ubuntu Linux 14.04

### ISSUE THREAD

**Issue by oche-jay** [trezor/cython-hidapi#12]
The same code I use to send a feature report on Mac OS and Windows just doesn't work on Linux.

Specifiaclly 

        buf = [0x0, 0x80, 0x25, 0x00, 0x00, 0x03] 
        res = self.hid_device.send_feature_report(buf);

returns a +ve integer on  Windows and OSX but -1 on Ubuntu 14.04. My guess is that somehow the map and join with chr in the method itself gives a wrong result, but i don't really understand this level of programming.
 Indeed running from an interactive python shell prints some weird characters to the console, but these are different from the equally weird characters that are printed on other OS.

       >>> buf = [0x0, 128, 0x25, 0x00, 0x00, 0x03] 
       >>> buff = ''.join(map(chr, buf))
       >>> print buff
       �%

**Comment by prusnak** [comment]
IIRC correctly the first byte of a feature report must be the length of the appended data. So it should look for example like this:

    buf = [0x05, 0x80, 0x25, 0x00, 0x00, 0x03]

**Comment by oche-jay** [comment]
Thank you sooo much. That fixed it!

Any idea why this would work on without the 1st byte being set on Windows and Mac, but not on Linux.
