### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [trezor/cython-hidapi#120]
Problem
---------
On aarch64, pip install hidapi builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install hidapi should download the wheels from pypi

@prusnak, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by prusnak** [comment]
Closed via https://github.com/trezor/cython-hidapi/pull/121

We'll publish aarch64 wheels on next version update
