### ISSUE TITLE
Release macOS Universal2 wheel

### ISSUE THREAD

**Issue by flit** [trezor/cython-hidapi#126]
Please release Universal2 wheels for macOS to support AArch64.

You can see an example Actions workflow for how to build the full range of wheels supported by cibuildwheel, including macOS universal2, in our workflow for cmsis-pack-manager: https://github.com/pyocd/cmsis-pack-manager/blob/main/.github/workflows/ci-build-wheel.yml (minus the Rust support that you don't need).

I'll see if I can find time to create a PR for this, and to switch to the `pypa/cibuildwheel` action instead of installing it via pip.

**Comment by prusnak** [comment]
Uploaded arm64 wheel here: https://pypi.org/project/hidapi/0.11.2/#files

I opted for not using universal to save space.
