### ISSUE TITLE
Compile error on Raspberry Pi.

### ISSUE THREAD

**Issue by alpha-ninja** [trezor/cython-hidapi#13]
Hey there,
I'm trying to compile cython-hidapi on a raspberry pi (raspbian) and get the following error:
`hid.pyx:14:46: Expected ')', found '*'`
(that's the line that extern's from * the `object` `PyUnicode_FromWideChar( ... )`)
I have absolutely no experience with cython, so it escapes me why this is...

**Comment by prusnak** [comment]
What version is Cython are you using? I suspect there is an old one. 0.22+ works for me.

**Comment by prusnak** [comment]
Closing, no info from reporter.
