### ISSUE TITLE
PS3 Controller doesn't show any data

### ISSUE THREAD

**Issue by pknessness** [trezor/cython-hidapi#134]
I tried this with my PS3 Controller, there's no data, even when I press some buttons and move the joysticks around.
I tried with a LUNA controller and it worked fine, is there something I need to do differently with a PS3 Controller?

**Comment by prusnak** [comment]
No idea. `cython-hidapi` is just a wrapper on top of hidapi, so you might want to ask there => https://github.com/libusb/hidapi

Maybe the PS3 controller is not HID compliant?
