### ISSUE TITLE
Problem with hidapi egg and python 3.10

### ISSUE THREAD

**Issue by smartavionics** [trezor/cython-hidapi#136]
Hi, I have been successfully building and using eggs for python 3.5 and 3.8 but the egg built for python 3.10 doesn't make the hidapi symbols visible. BTW I am still using hidapi 0.9.0 but I tried it with 0.11.2 and the behaviour is the same.

Having built the egg using 
```
/opt/python3.10/bin/python3 setup.py --without-libusb bdist_egg
```
I can then do

```
PYTHONPATH=dist/hidapi-0.9.0-py3.10-linux-x86_64.egg /opt/python3.10/bin/python3 -v
```
And then "import hid" prints lots of diagnostics but finishes with:
```
# extension module 'hid' loaded from '/home/markb/.cache/Python-Eggs/hidapi-0.9.0-py3.10-linux-x86_64.egg-tmp/hid.cpython-310-x86_64-linux-gnu.so'
# extension module 'hid' executed from '/home/markb/.cache/Python-Eggs/hidapi-0.9.0-py3.10-linux-x86_64.egg-tmp/hid.cpython-310-x86_64-linux-gnu.so'
import 'hid' # <zipimporter object "/home/markb/src/cython-hidapi.git/dist/hidapi-0.9.0-py3.10-linux-x86_64.egg/">
```

But, if you then do "dir(hid)" you don't see any of the hidapi symbols (e.g. enumerate)

```
>>> dir(hid)
['__builtins__', '__cached__', '__doc__', '__file__', '__name__', '__package__', '__spec__']
>>> 
```

However, if I unpack the egg and run python in that directory, import hid works correctly, i.e. 

```
>>> import hid
>>> dir(hid)
['__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__test__', 'device', 'enumerate', 'sys']
>>> 
```

Does anyone know what's going wrong here? Thanks.

**Comment by prusnak** [comment]
Does this method you use work with other .egg files (not hidapi)?

**Comment by smartavionics** [comment]
> Does this method you use work with Python 3.10 for other .egg files (not hidapi)?

Good question, I'll investigate.

**Comment by smartavionics** [comment]
I just tried it with pyserial and, yes, it works OK. I note however that pyserial doesn't use any C code, it's all python.
```
>>>import serial
...
import 'serial.serialposix' # <zipimporter object "/home/markb/src/pyserial.git/dist/pyserial-3.5-py3.10.egg/serial/">
import 'serial' # <zipimporter object "/home/markb/src/pyserial.git/dist/pyserial-3.5-py3.10.egg/">
>>> dir(serial)
['CR', 'EIGHTBITS', 'FIVEBITS', 'LF', 'PARITY_EVEN', 'PARITY_MARK', 'PARITY_NAMES', 'PARITY_NONE', 'PARITY_ODD', 'PARITY_SPACE', 'PortNotOpenError', 'PosixPollSerial', 'SEVENBITS', 'SIXBITS', 'STOPBITS_ONE', 'STOPBITS_ONE_POINT_FIVE', 'STOPBITS_TWO', 'Serial', 'SerialBase', 'SerialException', 'SerialTimeoutException', 'Timeout', 'VERSION', 'VTIMESerial', 'XOFF', 'XON', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'absolute_import', 'basestring', 'importlib', 'io', 'iterbytes', 'os', 'protocol_handler_packages', 'serial_for_url', 'serialposix', 'serialutil', 'sys', 'time', 'to_bytes', 'unicode']
>>> 
```

**Comment by prusnak** [comment]
> I just tried it with pyserial and, yes, it works OK. I note however that pyserial doesn't use any C code, it's all python.

Yeah, that's what I meant - to try this out with other Cython module, not with a pure Python module.

**Comment by smartavionics** [comment]
I think the simplest thing is for me to just unpack the egg and then it works OK.

Thanks for the quick response!
