### ISSUE TITLE
enumeration problem

### ISSUE THREAD

**Issue by mcsmark** [trezor/cython-hidapi#137]
i wanted to try pymcuprog and i get errors about no device found.
so i checked the module responsible and that is hidapi.
when i try :  py   -c "import hid; hid.device().open_path(hid.enumerate()[0]['path'])"
I get nothing. the samples to open the hid device direct using vid & pid also do not work.

i have a windows system and libusb installed and working. after i installed a filter driver i can see the connected device with libusb tools :
bus/device  idVendor/idProduct
bus-0/\\.\libusb0-0001--0x04d8-0x9018     04D8/9018
- Manufacturer : Microchip Technology Incorporated
- Product      : MPLAB® Snap ICD
- Serial Number: BUR190972701

But using hidapi i do not see it. it is supposed to work with libusb right?

i used the try.py sample and it does show some connected devices. so it is working partial. but why not for this device?
in windows manager it is under Microchip Tools and is named as Microchip WinUSB device. so that is most likely the problem, that is isnt a HID device. Anyone an idea how to fix this? since pymcuprog is using hidapi i assume it should work.

**Comment by prusnak** [comment]
`py -c "import hid; hid.device().open_path(hid.enumerate()[0]['path'])"`

this will open the first device - are you sure your device is the first one? 

change vendorID/productID on line 21 of try.py and paste the output of the script when you run it

**Comment by mcsmark** [comment]
sorry had no idea  hat it would select only 1.
the try.py i modified like this :
 h.open(0x4d8, 0x9018) 

that gives this output :

=============== RESTART: D:\Python38\cython-hidapi-master\try.py ===============
interface_number : 0
manufacturer_string : Logitech
path : b'\\\\?\\hid#vid_046d&pid_c52e&mi_00#8&131c0bb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
product_id : 50478
product_string : USB Receiver
release_number : 8961
serial_number : Љ
usage : 6
usage_page : 1
vendor_id : 1133

interface_number : 1
manufacturer_string : Logitech
path : b'\\\\?\\hid#vid_046d&pid_c52e&mi_01&col01#8&2508fe7d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
product_id : 50478
product_string : USB Receiver
release_number : 8961
serial_number : Љ
usage : 2
usage_page : 1
vendor_id : 1133

interface_number : 1
manufacturer_string : Logitech
path : b'\\\\?\\hid#vid_046d&pid_c52e&mi_01&col02#8&2508fe7d&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}'
product_id : 50478
product_string : USB Receiver
release_number : 8961
serial_number : Љ
usage : 1
usage_page : 12
vendor_id : 1133

interface_number : 1
manufacturer_string : Logitech
path : b'\\\\?\\hid#vid_046d&pid_c52e&mi_01&col03#8&2508fe7d&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}'
product_id : 50478
product_string : USB Receiver
release_number : 8961
serial_number : Љ
usage : 128
usage_page : 1
vendor_id : 1133

interface_number : 1
manufacturer_string : Logitech
path : b'\\\\?\\hid#vid_046d&pid_c52e&mi_01&col04#8&2508fe7d&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}'
product_id : 50478
product_string : USB Receiver
release_number : 8961
serial_number : Љ
usage : 1
usage_page : 65280
vendor_id : 1133

interface_number : 1
manufacturer_string : Logitech
path : b'\\\\?\\hid#vid_046d&pid_c52e&mi_01&col05#8&2508fe7d&0&0004#{4d1e55b2-f16f-11cf-88cb-001111000030}'
product_id : 50478
product_string : USB Receiver
release_number : 8961
serial_number : Љ
usage : 2
usage_page : 65280
vendor_id : 1133

interface_number : -1
manufacturer_string : American Power Conversion
path : b'\\\\?\\hid#vid_051d&pid_0002#7&1d105c6a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
product_id : 2
product_string : Back-UPS CS 500 FW:808.q7.I USB FW:q7
release_number : 6
serial_number : BB0607008104  
usage : 4
usage_page : 132
vendor_id : 1309

Opening the device
open failed
You probably don't have the hard-coded device.
Update the h.open() line in this script with the one
from the enumeration list output above and try again.
Done

so direct open the device using vid&pid does not work. further the enumeration output looks odd. 
anyway thanks for your help.

**Comment by mcsmark** [comment]
thank you for your quick response and help. ok i will contact pymcuprog and hope they can fix it.

**Comment by xedbg** [comment]
Solution: the device in question (Snap and PICkit4) need to be switched into a HID configuration ("AVR mode") using Microchip Studio or MPLABX
