### ISSUE TITLE
Windows 10 needs some other flags in open_device()

### ISSUE THREAD

**Issue by conurus** [trezor/cython-hidapi#14]
I had some code which used to work under Windows 7/8/8.1 and got a failed open_path under Windows 10. Had to make share_mode = FILE_SHARE_READ|FILE_SHARE_WRITE for both the enumerate case and the not enumerate case to get through. (Of course this is not the fix I don't know the most correct flags to pass.)

**Comment by prusnak** [comment]
This is not an issue in cython-hidapi but in the hidapi itself.

Also it seems it has been reported here already: https://github.com/signal11/hidapi/pull/189

Closing this one.
