### ISSUE TITLE
Update to HIDAPI v0.14.0

### ISSUE THREAD

**Issue by flozz** [trezor/cython-hidapi#151]
Hello,

HIDAPI v0.14.0 was released 3 days ago. Among other things, it fixes an annoying bug on macOS Ventura that causes all interfaces numbers to be `0`...

* https://github.com/libusb/hidapi/releases/tag/hidapi-0.14.0

Is it possible for you to update the Python bindings to allow us to benefit from this fix? :)

**Comment by benma** [comment]
Please do this and release an update as soon as possible - this bug (fixed in 0.14.0) is affecting BitBox02 users on macOS 13.3+. Thanks!

**Comment by prusnak** [comment]
Uploaded to PyPI: https://pypi.org/project/hidapi/0.14.0/

Enjoy!

**Comment by flozz** [comment]
Yeah! Thank you! :D

**Comment by benma** [comment]
Thank you!
