### ISSUE TITLE
Writing to a specific HID interface

### ISSUE THREAD

**Issue by tanky321** [trezor/cython-hidapi#152]
Hi,

Can HID-API be used to write to a specific interface on a multi-interface device? My custom device has an HID gamepad on interface 0, and a raw device on interface 1. Can I specify to write the data to interface 1? Apologies if this is trivial, very new to USB...

`interface_number : 0
manufacturer_string : ADEM
path : b'1-2.4.1:1.0'
product_id : 5322
product_string : PICTesting
release_number : 256
serial_number : 
usage : 0
usage_page : 0
vendor_id : 27908

interface_number : 1
manufacturer_string : ADEM
path : b'1-2.4.1:1.1'
product_id : 5322
product_string : PICTesting
release_number : 256
serial_number : 
usage : 0
usage_page : 0
vendor_id : 27908`

**Comment by prusnak** [comment]
You can use hidapi only to write to hid devices, not raw devices. For writing to raw devices you need libusb.

**Comment by tanky321** [comment]
Sorry, it is an HID device, basically just like the CCS example mentioned
in the docs. Difference is I have two interfaces, can I write to one of the
interfaces specifically?

**Comment by prusnak** [comment]
Use `open_path` to open specific path, for your example:
```
    h = hid.device()
    h.open_path(b'1-2.4.1:1.1')
```
