### ISSUE TITLE
Don't know how to compile chid.pxd

### ISSUE THREAD

**Issue by vmanish** [trezor/cython-hidapi#157]
Build fails for 32bit python2 with the following error:

C:\Python27x86\cython-hidapi> python .\setup.py build
running build
running build_ext
Compiling hid.pyx because it changed.
[1/1] Cythonizing hid.pyx
C:\Python27x86\lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Python27x86\cython-hidapi\hid.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'hid' extension
`error: Don't know how to compile chid.pxd`

Python
`Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)] on win32`

Build machine
`Windows 11 Enterprise x64`

Compiler
`Visual C++ compiler package for Python 2.7 - version 9.0.1.30729`

**Comment by prusnak** [comment]
Python 2 is unsupported.
