### ISSUE TITLE
Wheel for Python 3.12

### ISSUE THREAD

**Issue by flozz** [trezor/cython-hidapi#160]
Hello !

Python 3.12 was released this month. Is it possible for you to build/publish a wheel for it on PyPI? :)

**Comment by desmphil** [comment]
I have the same problem with 3.11

pi@FIT-68a957b:~ $ python3 --version
**Python 3.11.2**

sudo apt-get install python-dev libusb-1.0-0-dev libudev-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-dev-is-python3

E: Package 'python-dev' has no installation candidate

**CHANGED to include  python-dev-is-python3**


pi@FIT-68a957b:~ $ sudo pip install hidapi
Collecting hidapi
  Using cached hidapi-0.14.0.tar.gz (143 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools>=19.0 in /usr/local/lib/python3.11/dist-packages (from hidapi) (68.2.2)
Building wheels for collected packages: hidapi
  Building wheel for hidapi (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      /usr/local/lib/python3.11/dist-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_ext
      Compiling hid.pyx because it changed.
      [1/1] Cythonizing hid.pyx
      /tmp/pip-install-211lxr7_/hidapi_de821c2beb214dd9bae28d1957326287/.eggs/Cython-3.0.5-py3.11.egg/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-211lxr7_/hidapi_de821c2beb214dd9bae28d1957326287/hid.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'hid' extension
      error: unknown file type '.pxd' (from 'chid.pxd')
      [end of output]

**Comment by prusnak** [comment]
There is this error - https://github.com/trezor/cython-hidapi/actions/runs/6552643885/job/17796388898

Come up with a fix and I'll publish wheels for 3.12

**Comment by cmcqueen** [comment]
A missing `#include` to get the definition of `enum hid_bus_type` perhaps. I don't have access to a MacOS platform though.

**Comment by prusnak** [comment]
Fixed by https://github.com/trezor/cython-hidapi/commit/c9eec80d27b5e23055e0c675590f93c88ab49a88


Wheels for Python 3.12 pushed to PyPI - see https://pypi.org/project/hidapi/#files

Thanks @Youw!

**Comment by flozz** [comment]
Thank you very much @Youw and @prusnak! :D
