### ISSUE TITLE
Add wrapper for hid_get_report_descriptor

### ISSUE THREAD

**Issue by Youw** [trezor/cython-hidapi#165]
Introduced with https://github.com/libusb/hidapi/pull/451 in 0.14.0 as:
```c
int HID_API_EXPORT_CALL hid_get_report_descriptor(hid_device *dev, unsigned char *buf, size_t buf_size);
```

**Comment by OrhanYigitDurmaz** [comment]
ping?

**Comment by Youw** [comment]
This is an open-source project, external contributions are always welcome.

**Comment by prusnak** [comment]
added via https://github.com/trezor/cython-hidapi/pull/186
