### ISSUE TITLE
Migration to hidraw as a default backend for pip package

### ISSUE THREAD

**Issue by Youw** [trezor/cython-hidapi#166]
As of #162 hidraw backend on Linux is the default one built by the setup.py.
Changing the default for all upstream/pip users would probably break a lot of applications/projects due to differences between libusb and hidraw backends.

Need to comeup with the migration plan for all users.

**Comment by Youw** [comment]
I think one of the easiet ways is to switch to hidraw as a default when HIDAPI bumps its version to 1.0.
But we could also consider some alternatives.

**Comment by prusnak** [comment]
Updated wheels action in https://github.com/trezor/cython-hidapi/commit/690824080c360c60276e4da0f873bd3df223a502 to use libusb so we don't forget about it.

**Comment by bearsh** [comment]
so it seems the default backend has been changed in 1fceee664338946cd4a998b9152e60a3d936cdb5. I'm not really happy doing this without a major version bump. this kind of breaks the api! 

@prusnak  is there a may to continue to use the libusb backend?

**Comment by prusnak** [comment]
> @prusnak  is there a may to continue to use the libusb backend?

Yes, build from source and set env variable HIDAPI_WITH_LIBUSB to 1

**Comment by bearsh** [comment]
maybe then the install section in the [readme](https://github.com/trezor/cython-hidapi?tab=readme-ov-file#install) should also be changed to reflex this...

it would also be nice to mention the backend change in the readme...

**Comment by prusnak** [comment]
> maybe then the install section in the [readme](https://github.com/trezor/cython-hidapi?tab=readme-ov-file#install) should also be changed to reflex this...
> 
> 
> 
> it would also be nice to mention the backend change in the readme...

Please send a PR
