### ISSUE TITLE
Make a release that supports Cython 3 and later

### ISSUE THREAD

**Issue by hegjon** [trezor/cython-hidapi#168]
Fedora Linux 39 comes with Cython 3 as standard. `master` cointains #159 that works for Cython 3.

**Comment by CuriouslyCurious** [comment]
Same problem for me on Alpine Linux.

**Comment by prusnak** [comment]
hidapi 0.14.0.post1 released with the fixes: https://pypi.org/project/hidapi/0.14.0.post1/#files
