### ISSUE TITLE
Installation fails when cython is not already installed

### ISSUE THREAD

**Issue by c1728p9** [trezor/cython-hidapi#17]
In setup.py Cython is imported before it has been installed, which causes the following exception:
```
C:\Russ\projects\github\cython-hidapi>pip install hidapi
Collecting hidapi
  Using cached hidapi-0.7.99-6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\russ\appdata\local\temp\pip-build-j6wqrh\hidapi\setup.p
y", line 4, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
```

**Comment by prusnak** [comment]
Could you please send a pull request? Or at least indicate what needs to be done?

**Comment by c1728p9** [comment]
Created #18 .  It doesn't fix the problem yet, but I think something like that needs to be done.  I'm still investigating.  Let me know if you have any ideas.

**Comment by prusnak** [comment]
I see. Let's close this one and follow #18.
