### ISSUE TITLE
Feature request: Add wheel for "musllinux"

### ISSUE THREAD

**Issue by pilotak** [trezor/cython-hidapi#170]
It would be perfect to build musllinux compatible wheel. It then can be easily intergrated into ie. Home Assistant

**Comment by prusnak** [comment]
Musl added in https://github.com/trezor/cython-hidapi/commit/e90217cf04cc5621881aae45db8350974a5a254c

Wheels uploaded to PyPI: https://pypi.org/project/hidapi/0.14.0/#files
