### ISSUE TITLE
add supporting for hid_get_report_descriptor

### ISSUE THREAD

**Issue by sinseraph** [trezor/cython-hidapi#172]
Please add a API fucntion according to new feature in hidapi-0.14.0
general: add hid_get_report_descriptor API function (https://github.com/libusb/hidapi/pull/451)

I need report_descriptor to figure out different bLength of multiple enumerates, thanks.

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/cython-hidapi/issues/165
