### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [trezor/cython-hidapi#176]
It would be good to cut off a new release to include [this cython requirement patch](https://github.com/trezor/cython-hidapi/commit/749da6931f57c4c30596de678125648ccfd6e1cd). Thanks!

**Comment by prusnak** [comment]
hidapi 0.14.0.post1 released with the fixes: https://pypi.org/project/hidapi/0.14.0.post1/#files

**Comment by chenrui333** [comment]
got some file missing issue

```
 FileNotFoundError: [Errno 2] No such file or directory:
'/private/tmp/keepkey-agent--hidapi-20240723-10954-cn1m1k/hidapi-0.14.0.post1/README.md'
```

relates to https://github.com/Homebrew/homebrew-core/pull/178205

**Comment by prusnak** [comment]
> got some file missing issue

hopefully this is fixed with https://pypi.org/project/hidapi/0.14.0.post2/

**Comment by chenrui333** [comment]
post2 works for us, thanks!
