### ISSUE TITLE
Open failed through python but not C

### ISSUE THREAD

**Issue by JeWe37** [trezor/cython-hidapi#177]
Rather strange issue: If I use the following code:
```python
import hid
hid.device().open_path("/dev/hidraw0".encode())
```
I get:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 2, in <module>
    hid.device().open_path("/dev/hidraw0".encode())
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
```
(tested on Debian bookworm which uses 0.9.0-post3, hence the odd line numbers, but the same error occurs in the builds from pipy). Permissions are not an issue, this is being run as root.

However, when I do the exact same thing in a C program:
```C
#include <stdio.h>
#include <hidapi/hidapi.h>

int main() {
        hid_device* dev = hid_open_path("/dev/hidraw0");
        printf("%lld\n", dev);
        return 0;
}
```
this prints `367460893344`, which is not `NULL` and thus shouldn't throw an error when using `cython-hidapi`?

**Comment by jonasmalacofilho** [comment]
One thing that comes to mind is that with `import hid` you might be using the LibUSB hidapi backend, which justifiably can't open `/dev/hidraw*`.

And in C, since you're doing it explicitly, you've almost certainly linked to the hidraw hidapi backend, so it works as expected.

**Comment by JeWe37** [comment]
That fixed it! Thanks
