### ISSUE TITLE
Python 3.13 Wheels

### ISSUE THREAD

**Issue by multiplemonomials** [trezor/cython-hidapi#185]
Hello, we use your library on the mbed-ce/mbed-os project, but installation is difficult for Windows users because there are no Python 3.13 wheels published to PyPi.  Would you be able to publish them please?  In the meantime we will have to recommend our Windows users to not use python 3.13.

**Comment by asdstevenc** [comment]
Hi, is there an update on this? Thank you!

**Comment by prusnak** [comment]
Version 0.14.0.post3 pushed to PyPI: https://pypi.org/project/hidapi/0.14.0.post3/
