### ISSUE TITLE
Compile error on OSX

### ISSUE THREAD

**Issue by xMrWhite** [trezor/cython-hidapi#19]
Installed /Users/ag/projects/csc490-arm/cython-hidapi/.eggs/Cython-0.23.4-py2.7-macosx-10.10-x86_64.egg
    /Users/ag/virtualenvs/csc490-arm/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.7.99-8' to '0.7.99.post8'
      normalized_version,
    running build
    running build_ext
    building 'hid' extension
    error: unknown file type '.pxd' (from 'chid.pxd')```

**Comment by StickerFiend** [comment]
You need to install Cython.

pip install cython
