### ISSUE TITLE
"open failed" when trying to open device on Raspberry Pi

### ISSUE THREAD

**Issue by Sharp6** [trezor/cython-hidapi#23]
Hi! 

I tried to compile python-hidapi on RPi. Notwithstanding some warnings, no real errors are thrown. However, when I connect a USB keyboard to the Pi and try to the try.py script, I get an error "open failed". 

The listing from hid.enumerate() shows the keyboard with vendor_id 1452 and product_id 545, so I added 0x5AC and 0x221 as arguments in the try.py script.

Am I doing something wrong, or does this mean something is wrong with my install? I wanted to test with a keyboard first to ensure that cython-hidapi works on my Pi before acquiring the hardware I actually want to use.

**Comment by bardsley** [comment]
similiar problem for me was solved by sudo, apparently standard pi user doesn't have read access to USB

**Comment by prusnak** [comment]
Ok, so this is udev permissions issue. Closing
