### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by repjak** [trezor/cython-hidapi#26]
Would you consider uploading also [wheel](http://pythonwheels.com/) archive to PyPI at least for some platforms? That would substantially simplify installation process on those platforms.

**Comment by prusnak** [comment]
If you tell me what to do, I'll do it.

**Comment by prusnak** [comment]
I just executed `python setup.py sdist bdist_wheel upload`. Is that enough?

(I can see `trezor-0.6.12-py2-none-any.whl` at https://pypi.python.org/pypi/trezor)

**Comment by prusnak** [comment]
Ah, sorry. I thought this was about `python-trezor` module).

**Comment by prusnak** [comment]
When I run `python setup.py bdist_wheel upload` for cython-hidapi I got this error:

``
Submitting /home/stick/work/trezor/cython-hidapi/dist/hidapi-0.7.99.post12-cp27-none-linux_x86_64.whl to https://pypi.python.org/pypi
Upload failed (400): Binary wheel for an unsupported platform
error: Upload failed (400): Binary wheel for an unsupported platform
```

Please advise.

**Comment by laliebijard** [comment]
Thank you for the prompt response.

Building wheels for C-extensions is currently only possible on Windows and Mac OS X (see relevant issue here: https://github.com/pypa/interoperability-peps/issues/39).

**Comment by prusnak** [comment]
I don't use Windows nor OS X, so I guess we are stuck here. Unless you want to become a maintainer for Windows and OS X builds, do you?

**Comment by laliebijard** [comment]
Good, I'll let my fellow developers know about this option. Thanks for now.

**Comment by prusnak** [comment]
@repjak any updates?

**Comment by repjak** [comment]
Sorry for late reply. I'm not going to have time to become a maintainer in the nearest future. So I'm closing the issue.
