### ISSUE TITLE
Problem installing hidapi on RPi / raspbian

### ISSUE THREAD

**Issue by shermarama** [trezor/cython-hidapi#33]
I'm having trouble installing hidapi on a Raspberry Pi running raspbian - I get "error: unknown file type '.pyx' (from 'hid.pyx')". I was wondering whether this was anything to do with cython, and saw on an RPi-related closed issue that you recommended cython 0.22+. I've upgraded cython from 0.21.1 to 0.24.1 and the error is just the same afterwards. What else might the problem be?

**Comment by prusnak** [comment]
Old setuptools.
 
At least version 19 is required.

**Comment by shermarama** [comment]
Ah, that's got it, thank you! The setuptools version was 5.5.1, and when I tried to upgrade it said it was the newest version; I installed 25.0.0 manually, and then was able to install hidapi.

**Comment by prusnak** [comment]
Ok, then. Please close the issue.
