### ISSUE TITLE
upload AppVeyor wheel builds to PyPi

### ISSUE THREAD

**Issue by benoit-pierre** [trezor/cython-hidapi#34]
Now that AppVeyor support is working, it would be great if the resulting builds were uploaded to PyPi.

**Comment by prusnak** [comment]
What commands should I issue to achieve that?

**Comment by benoit-pierre** [comment]
- go to [AppVeyor](https://ci.appveyor.com/)
- login with GitHub
- click `New Project` and add `cython-hidapi`
- click `New Build` to build the current head
- download the wheel for each job (click on the job and then on `Artifacts`)
- upload the wheels with `twine`

AppVeyor will automatically build each new commit to master. If you want, I can configure it to deploy the wheels to the corresponding GitHub release when a new tag is pushed (so they are available on GitHub too, and it's easier to download them for pushing to PyPi).

**Comment by benoit-pierre** [comment]
Any progress on this?

**Comment by prusnak** [comment]
Uploaded here:

https://pypi.python.org/pypi/hidapi/0.7.99.post18

Thanks for the pointers!
