### ISSUE TITLE
Can't install cython-hidapi within cygwin (sys.platform selection logic in setup.py doesn't account for it)

### ISSUE THREAD

**Issue by mmortal03** [trezor/cython-hidapi#35]
I've been trying to install cython-hidapi on Windows within cygwin, and ran into the following error:

> $ pip install hidapi
> Collecting hidapi
>   Using cached hidapi-0.7.99.post17.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-W1qbyY/hidapi/setup.py", line 86, in <module>
>         ext_modules = modules,
>     NameError: name 'modules' is not defined
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-W1qbyY/hidapi/

It looks like the cause is that the sys.platform selection logic in setup.py doesn't account for Cygwin's sys.platform string being "cygwin".

Replacing line 44 with the following seems to work around the issue (if, indeed, a cygwin install should be treated the same as Windows), though I haven't been successful with having it actually detect a device yet:

if sys.platform.startswith('win') or sys.platform.startswith('cygwin'):

**Comment by prusnak** [comment]
Are you able to successfully build the module after the change?

**Comment by mmortal03** [comment]
Yes, in the sense that adding "import hid" to a python script doesn't cause any errors, and the underlying hidapi properly builds, including hidtest.exe which does detect devices. I'm also able to, from there, build hidapi-testgui.exe once I include the hidapi-externals, which also detects devices. 
(I realize that hidtest and hidapi-testgui are not specific to cython-hidapi, but to the underlying hidapi).

The remaining issue that I'm seeing is that while hid.enumerate() runs, it doesn't detect any devices, contrary to what the underlying hidapi executables have shown to be capable of. 

I don't know if this is separate issue, or if it means that something in cython-hidapi didn't properly compile within cygwin.

As an aside, doesn't python-trezor also use this, or does it just independently use hidapi? My next step would be to get cython-hidapi to detect devices, and then get python-trezor working. (The latter also compiles, but doesn't detect my trezor.)

**Comment by prusnak** [comment]
Added cygwin to `setup.py` in https://github.com/trezor/cython-hidapi/commit/d63a23070063b9110330fc4f5ce714e2809978b8

python-trezor just uses `import hid`, so yes cython-hidapi is being used

Not sure about the issue you see with cygwin build not enumerating the devices, but the original issue is solved, thus I am closing this.

Feel free to open new issue about this, but unfortunately I don't have resources to hunt down cygwin problems. :-/
