### ISSUE TITLE
Optionally use system hidapi library?

### ISSUE THREAD

**Issue by Flameeyes** [trezor/cython-hidapi#39]
I would like to package cython-hidapi for Gentoo Linux, but I have some concerns about using a bundled copy of hidapi, in particular because we allow users to install multiple Python version (2.7+3.4+3.5, etc), and so the duplication of a library that is already in the system feels a bit awkward.

While I agree the current situation makes sense for default, would it be possible to have an option to link against the system copy?

Thanks!

**Comment by prusnak** [comment]
Sure. Will you create a pull request for that?

**Comment by Flameeyes** [comment]
Will look to do so!

**Comment by prusnak** [comment]
Hm, check https://github.com/trezor/cython-hidapi/blob/master/setup.py#L15

I now remember somebody did that already.

**Comment by Flameeyes** [comment]
Uh! I somehow missed it, I guess nothing to see here, I'll just use that, sorry for the noise :)
