### ISSUE TITLE
open() fails when called twice

### ISSUE THREAD

**Issue by slobodan-ilic** [trezor/cython-hidapi#4]
Hi Pavol,

When I call open() twice on the same hid.device() object, I get an IOError. So I always pair up the open() and close() calls. However, during the long-running reading process, if an error (for whichever reason) occurs, I might lose the reference to the original object hid.device(). If this happens, I have no way of closing the device again, and each new call to  open() will result in a IOError. Here is the code to reproduce the mentioned behavior:

import hid

h = hid.device()
h.open(vid, pid)
h.close() # everything works fine

h.open(vid, pid)
h = hid.device() # lose the reference to the opened device
h.close() #doesn't close the device and I have no way of getting the handle to the USB buffer again

h.open(vid, pid) # results in a IOError
h.read(5) # crashes python.exe

So, I was wondering, is this the expected behavior, and should I implement the higher-level logic to handle this (which could be complicated, because of multiple processes communicating), or could the additional protection be implemented?

Thanks for your time,

Best,
Slobodan

**Comment by misisnik** [comment]
@slobodan-ilic have you solved this (I have the same problem) ??
Thanks Mike

**Comment by slobodan-ilic** [comment]
@misisnik Hey Mike, I haven't been using this HID api for a while now. But I wasn't able to resolve it at the time. The workaround was to keep track of the object state somewhere in a global. Based on that state, you decide which actions you want to (and can) take on the api.

**Comment by prusnak** [comment]
Let's track the object state in Python then and don't call open twice.
