### ISSUE TITLE
why is setuptools required at runtime?

### ISSUE THREAD

**Issue by benoit-pierre** [trezor/cython-hidapi#42]
https://github.com/trezor/cython-hidapi/blob/9227279a5e893b525136a46f081ae27ff2f77947/setup.py#L123

I don't see any related import in the code.

**Comment by prusnak** [comment]
Old setuptools don't support compilation of Cython, this hack fixes
the issue.

**Comment by benoit-pierre** [comment]
OK.

**Comment by benoit-pierre** [comment]
Let's revisit in a few years when `setuptools<19` is considered too old to be supported... :P
