### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by bjacquin** [trezor/cython-hidapi#43]
Hi,

I'd like to make a release of cython-hidapi for gentoo, are you planning to create a release since you forked ?

Thanks

**Comment by prusnak** [comment]
Not sure what you mean ... latest release pushed to PyPI is 0.7.99post20 which is the same version as we have in master (all changes in git after the aforementioned release are just wrt building in travis/appveyor and do not affect anything else).

**Comment by bjacquin** [comment]
Indeed, you are right, I did not look at pypi.

See https://github.com/gentoo/gentoo/pull/5903 for inclusion request in Gentoo ebuild tree.
