### ISSUE TITLE
raspberrypi usb hid read errors

### ISSUE THREAD

**Issue by jrz90000** [trezor/cython-hidapi#46]
I succeeded in the Mac OS and winodws, but I couldn't send and receive hid data when I was in raspberry pie.

How do I debug it?

**Comment by prusnak** [comment]
You need to create udev file for your device similar to 
https://raw.githubusercontent.com/trezor/trezor-common/master/udev/51-trezor.rules on Linux. Otherwise it won't work with normal user, just root.

**Comment by jrz90000** [comment]
I tried putting the content into /usr/lib/udev/rules.d/51-trezor.rules and /etc/udev/rules.d/51-trezor.rules, changing ATTR {idVendor} to my id , Root management, or can not send and receive hid information.

**Comment by prusnak** [comment]
Have you also changed idProduct ? Please paste the contents of your udev file

**Comment by jrz90000** [comment]
I try reboot,but 



/usr/lib/udev/rules.d/51-trezor.rules:
`# TREZOR: The Original Hardware Wallet
# https://trezor.io/
# Put this file into /usr/lib/udev/rules.d

# TREZOR
SUBSYSTEM=="usb", ATTR{idVendor}=="534c", ATTR{idProduct}=="0001", MODE="0660", GROUP="plugdev", TAG+$
KERNEL=="hidraw*", ATTRS{idVendor}=="534c", ATTRS{idProduct}=="0001",  MODE="0660", GROUP="plugdev", $

# TREZOR v2
SUBSYSTEM=="usb", ATTR{idVendor}=="1209", ATTR{idProduct}=="53c0", MODE="0660", GROUP="plugdev", TAG+$
SUBSYSTEM=="usb", ATTR{idVendor}=="1209", ATTR{idProduct}=="53c1", MODE="0660", GROUP="plugdev", TAG+$
KERNEL=="hidraw*", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="53c0",  MODE="0660", GROUP="plugdev", $
KERNEL=="hidraw*", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="53c1",  MODE="0660", GROUP="plugdev", $

# TREZOR Raspberry Pi Shield
SUBSYSTEM=="usb", ATTR{idVendor}=="0525", ATTR{idProduct}=="a4ac", MODE="0660", GROUP="plugdev", TAG+$
KERNEL=="hidraw*", ATTRS{idVendor}=="0525", ATTRS{idProduct}=="a4ac",  MODE="0660", GROUP="plugdev", $

`


/etc/udev/rules.d/51-trezor.rules
`# TREZOR: The Original Hardware Wallet
# https://trezor.io/
# Put this file into /usr/lib/udev/rules.d

# TREZOR
SUBSYSTEM=="usb", ATTR{idVendor}=="534c", ATTR{idProduct}=="0001", MODE="0660", GROUP="plugdev", TAG+$
KERNEL=="hidraw*", ATTRS{idVendor}=="534c", ATTRS{idProduct}=="0001",  MODE="0660", GROUP="plugdev", $

# TREZOR v2
SUBSYSTEM=="usb", ATTR{idVendor}=="1209", ATTR{idProduct}=="53c0", MODE="0660", GROUP="plugdev", TAG+$
SUBSYSTEM=="usb", ATTR{idVendor}=="1209", ATTR{idProduct}=="53c1", MODE="0660", GROUP="plugdev", TAG+$
KERNEL=="hidraw*", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="53c0",  MODE="0660", GROUP="plugdev", $
KERNEL=="hidraw*", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="53c1",  MODE="0660", GROUP="plugdev", $

# TREZOR Raspberry Pi Shield
SUBSYSTEM=="usb", ATTR{idVendor}=="0525", ATTR{idProduct}=="a4ac", MODE="0660", GROUP="plugdev", TAG+$
KERNEL=="hidraw*", ATTRS{idVendor}=="0525", ATTRS{idProduct}=="a4ac",  MODE="0660", GROUP="plugdev", $

`
the are my macos usb info:
<img width="502" alt="qq20171025-222104 2x" src="https://user-images.githubusercontent.com/7508776/32003971-51a608ec-b966-11e7-815d-ae64b9a713aa.png">

**Comment by prusnak** [comment]
I don't see anything obvious. Maybe ask on Raspberry Pi forums. This is not related to library itself, but to udev. Closing.

**Comment by jrz90000** [comment]
Thanks
