### ISSUE TITLE
open failed on Raspberry Pi

### ISSUE THREAD

**Issue by vfilimonov** [trezor/cython-hidapi#47]
Hello, I've got some problems in accessing hidraw device from cython-hidapi library on Raspberry Pi. 

I've set up permissions in `/etc/udev/rules.d`, so I get `rw-` permissions on connection:
```
(system3) pi@raspberrypi:~ $ ls -l /dev/h*
crw-rw-rw- 1 root plugdev 248,   0 Feb 18 11:41 /dev/hidraw0
crw------- 1 root root     10, 183 Feb 18 01:17 /dev/hwrng
```
The device is visible in `hid.enumerate()`:
```
(system3) pi@raspberrypi:~ $ python -c "import hid; print(hid.enumerate())"
[{'product_id': 41042, 'usage_page': 0, 'interface_number': 0, 'product_string': '', 'serial_number': '', 'vendor_id': 1241, 'manufacturer_string': '', 'path': b'0001:0005:00', 'usage': 0, 'release_number': 256}]
```
But when I try to open it, I get `OSError`:
```
(system3) pi@raspberrypi:~ $ python -c "import hid; h = hid.device(); h.open(0x04d9, 0xa052)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed
```

I tried both builds; with and without `libusb` and neither worked..

At the same time I can read straight from the `/dev/hidraw0` (in python as well) - and it works fine. And the same device on osx works fine with `cython-hidapi`.

I would appreciate any suggestion!

**Comment by prusnak** [comment]
Is user `pi` in the group `plugdev`?

**Comment by vfilimonov** [comment]
Hello Pavol,

yes, he is:
```
(system3) pi@raspberrypi:~ $ groups
pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi hid-users
```
and it has read/write access to `/dev/hidraw0`

**Comment by prusnak** [comment]
For TREZOR we use the following udev file: https://github.com/trezor/trezor-common/blob/master/udev/51-trezor.rules

Please make sure yours is the same (except vendorid/productid).

Also which distro do you use?

**Comment by vfilimonov** [comment]
Thank you, Pavol! 

Eventually, only one record that I had in `/etc/udev/rules.d98-co2mon.rules` was not enough:
```
KERNEL=="hidraw*", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="a052", GROUP="plugdev", MODE="0666"
```

I've tried a couple of things (among those that did not work was combining `KERNEL=="hidraw*", SUBSYSTEM=="usb", ...` in a single record that was suggested in a couple of places).

But what has solved the issue, is to have `KERNEL` and `SUBSYSTEM` as separate records, like in your example:
```
KERNEL=="hidraw*", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="a052", GROUP="plugdev", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="a052", GROUP="plugdev", MODE="0666"
```
