### ISSUE TITLE
Fails to build on Windows

### ISSUE THREAD

**Issue by cryptosig** [trezor/cython-hidapi#5]
I think the problem is because I have multiple versions of Visual Studio installed, (2008 express, 2012 full). The problem could be solved if I compiled on a dedicated VM with only VS 2008

Stack trace:
<blockquote>
<p>C:\GitHub\cython-hidapi>python setup.py build</p>
<p>running build</p>
<p>running build_ext</p>
<p>skipping 'hid.c' Cython extension (up-to-date)</p>
<p>building 'hid' extension</p>
<p>Traceback (most recent call last):</p>
<p>  File "setup.py", line 63, in <module></p>
<p>    ext_modules = modules</p>
<p>  File "C:\Python27\lib\distutils\core.py", line 152, in setup</p>
<p>    dist.run_commands()</p>
<p>  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)</p>
<p>  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command</p>
    cmd_obj.run()</p>
<p>  File "C:\Python27\lib\distutils\command\build.py", line 127, in run</p>
    self.run_command(cmd_name)</p>
<p>  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command</p>
    self.distribution.run_command(command)</p>
<p>  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command</p>
    cmd_obj.run()</p>
<p>  File "C:\Python27\lib\site-packages\Cython\Distutils\build_ext.py", line 163,
in run</p>
    _build_ext.build_ext.run(self)</p>
<p>  File "C:\Python27\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()</p>
<p>  File "C:\Python27\lib\site-packages\Cython\Distutils\build_ext.py", line 171,
in build_extensions</p>
<p>    self.build_extension(ext)</p>
 <p> File "C:\Python27\lib\distutils\command\build_ext.py", line 499, in build_exte
nsion</p>
<p>    depends=ext.depends)</p>
<p>  File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()</p>
<p>  File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)</p>
<p>  File "C:\Python27\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsal
l</p>
<p>    raise ValueError(str(list(result.keys())))</p>
<p>ValueError: [u'path']</p>
</blockquote>

**Comment by c1728p9** [comment]
I had a very similar problem.  Turns out it was because I had x64 python installed and only had the x86 visual studio tools installed.  Re-running the installer and selecting "X64 Compilers and Tools" allowed me to install.

**Comment by prusnak** [comment]
Thanks for the info. Closing for now. Feel free to reopen if the problem persists.
