### ISSUE TITLE
'open failed' for bluetooth hid devices

### ISSUE THREAD

**Issue by kypalmer** [trezor/cython-hidapi#59]
Operating System: OsX

Behavior: 

- running python3 under sudo (REPL)
- hid.enumerate() shows all bluetooth and usb connected HID devices. 
- device.open succeeds in opening a USB keyboard (reads work)
- device.open & device.open_path fail with a bluetooth keyboard. 'OSError: open failed'

Expected Behavior: a connection to be opened to any HID device in hid.enumerate()

reproduction: 
```
>>> import hid
>>> hid.enumerate() // several HID devices listed
>>> h = hid.device()
>>> h.open(1452, 544) // apple USB keyboard -- works
>>> h.close()
>>> h.open(1452, 569) // apple bluetooth keyboard -- OSError: open failed
```

I assumed from Apple's [bluetooth docs](https://developer.apple.com/library/archive/documentation/DeviceDrivers/Conceptual/Bluetooth/BT_Develop_BT_Apps/BT_Develop_BT_Apps.html#//apple_ref/doc/uid/TP30000997-CH216-TP9) that bluetooth HID access would work the same as USB. 

Any thoughts? It's my first attempt at using the library, so I may be doing something wrong. 

Cheers

**Comment by prusnak** [comment]
I guess this is a question for the upstream project: https://github.com/signal11/hidapi

cython-hidapi is just a Python wrapper

**Comment by kypalmer** [comment]
Thanks,

I'll give it a go there.
