### ISSUE TITLE
read() function has no `buf` or `report_id` argument

### ISSUE THREAD

**Issue by mrdimfox** [trezor/cython-hidapi#60]
It is not possible to send an Input report to device because there is no way to set report id, as it said into hidapi docs here: [link to docs](https://github.com/signal11/hidapi/blob/master/hidapi/hidapi.h#L208).

**Comment by prusnak** [comment]
Can you add a pull request for this change? Thanks!

**Comment by mrdimfox** [comment]
Yeap, sure. I can do it.

**Comment by prusnak** [comment]
@mrdimfox ping

**Comment by mrdimfox** [comment]
@prusnak I was wrong about this function. It just read everything from INTERRUPT IN endpoint so there is no need to pass report id inside. It probably will appear in a report buffer read from HID device and returned by this func.

Issue can be closed.
