### ISSUE TITLE
`get_manufacturer_string`, `get_product_string` and `get_serial_number_string` should rise IOError

### ISSUE THREAD

**Issue by mrdimfox** [trezor/cython-hidapi#61]
For example here in `get_serial_number_string`:
```
      cdef int r = hid_get_serial_number_string(self._c_hid, buff, 255)
      if not r:
          return U(buff)
```
method should raise `IOError` in else-branch. According to hidapi docs function `hid_get_serial_number_string` returns `-1` if error occurs.

**Comment by prusnak** [comment]
Can you add a pull request for this change? Thanks!
