### ISSUE TITLE
unable to build for python kivy mobile app

### ISSUE THREAD

**Issue by lakshyacis** [trezor/cython-hidapi#69]
As I am creating an app in kivy python using buildozer a wrapper for python-for-android where a buildozer.spec file needs to be maintained and I simply wrote hidapi as requirement but it seems not working when says import hid

**Comment by prusnak** [comment]
What does it say?

**Comment by lakshyacis** [comment]
@prusnak it says
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
12-07 18:20:51.496 9575 9603 I python : Python for android ended.

**Comment by prusnak** [comment]
So it seems your system is missing one of these libraries. Try adding `libhidapi` or `libhidapi-hidraw` or `ibhidapi-libusb` to your spec file.

I am closing this as this is not a cython-hidapi issue, but rather packaging issue of your app.

**Comment by lakshyacis** [comment]
Android NDK: WARNING:/home/cis/demokivy/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/jni/application/src/Android.mk:main: non-system libraries in linker flags: -lpython3.7m    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
/home/cis/.buildozer/android/platform/android-ndk-r17c/build/core/build-binary.mk:688: Android NDK: Module main depends on undefined modules: python_shared

https://pastebin.com/zPMfz3su

please check this spec file

**Comment by prusnak** [comment]
I am not doing your homework for you. Please ask at kivy/buildozer channels if you need help.
