### ISSUE TITLE
fatal error: hidapi.h: No such file or directory  #include "hidapi.h"

### ISSUE THREAD

**Issue by lakshyacis** [trezor/cython-hidapi#70]
I got this issue while building

running install
running build
running build_ext
skipping 'hid.c' Cython extension (up-to-date)
building 'hid' extension
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/cis/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/cis/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/cis/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/cis/trezortry/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/testapp11/include/python3.7 -DNDEBUG -g -fwrapv -O3 -Wall -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/cis/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/cis/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/cis/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/cis/trezortry/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/testapp11/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -I/home/cis/trezortry/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include -fPIC -Ihidapi/hidapi -I/usr/include/libusb-1.0 -I/home/cis/trezortry/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/cis/trezortry/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c hid.c -o build/temp.linux-x86_64-3.7/hid.o
hid.c:569:20: fatal error: hidapi.h: No such file or directory
 #include "hidapi.h"
                    ^
compilation terminated.
error: command '/usr/bin/ccache' failed with exit status 1

**Comment by prusnak** [comment]
Your system does not have libhidapi installed.
