### ISSUE TITLE
can be build hidapi for android ?

### ISSUE THREAD

**Issue by surbhicis** [trezor/cython-hidapi#71]
As I am developing an android app in python and it needs to use hidapi support so is this possible to build it for android?
 as I saw there is no build process for android platform in setup.py

**Comment by prusnak** [comment]
It should be possible. Try it out and let us know about the result.

**Comment by surbhicis** [comment]
but there is no build process for android platform in setup.py

**Comment by prusnak** [comment]
Figure out how to add it by studying documentation and once you figured it out send a pull request with the change. Thanks

**Comment by surbhicis** [comment]
sure

**Comment by prusnak** [comment]
Also related to https://github.com/trezor/cython-hidapi/issues/69

**Comment by surbhicis** [comment]
thanks ,let me check and if finds something useful will create PR as well
