### ISSUE TITLE
Issue when import hid in a python program

### ISSUE THREAD

**Issue by ClaraS-dev** [trezor/cython-hidapi#74]
Hello,

I have an issue when I try to use hidapi to connect to an usb device.
The error is
File "test_raspberry_connected.py", line 2, in <module>
    import hid
File "usr/local/lib/python3.7/dist-packages/hid/__init__.py, line 30, in <module>
   raise ImportError(error)
ImportError: Unable to load any of the following libraries: libhidapi-hidraw.so libhidapi-hidraw.so.o ....... hidapi.dll libhidapi-0.dll

Avez vous une idée pour résoudre ce problème ?

Ce qui est étrange aussi c'est que toutes les autres librairies sont installées dans /usr/lib/python3 alors que hidapi est dans /usr/local/lib/python3.7/dist-packages, je ne sais pas si ça peut jouer.

Si quelqu'un peut m'aider à me débloquer ce serait vraiment top !

Clara

**Comment by prusnak** [comment]
Install libhidapi on your system.
