### ISSUE TITLE
hid_enumerate returns empty paths on macOS Mojave and Catalina

### ISSUE THREAD

**Issue by conurus** [trezor/cython-hidapi#77]
This only happens on Mojave and Catalina and also the app is in a sandbox signed with hardened runtime. I tried this fix in libusb/hidapi and it worked so it is just a matter using that label: https://github.com/libusb/hidapi/pull/120

**Comment by prusnak** [comment]
Duplicate of https://github.com/trezor/cython-hidapi/issues/65

**Comment by prusnak** [comment]
Can you try building the version from master to see if it works for you?
