### ISSUE TITLE
Empty list on read().

### ISSUE THREAD

**Issue by AlexTochka** [trezor/cython-hidapi#78]
The read() function does not work in Windows 10, it always returns an empty list. Checked on 32 bit and 64 bit versions of Windows 10. On Linux, it works fine.

**Comment by AlexTochka** [comment]
Clarification. Returns an empty list when set_nonblocking (1). If set_nonblocking (0), then blocks the program. Most likely there are some problems with permissions on the USB device file in Windows. There was such a topic in the hidapi library itself, which was fixed.

**Comment by AlexTochka** [comment]
Addition. When building the package, very old source files (2016) of the hidapi project are used. These source files have code that does not allow them to work correctly in Windows 10 (enumeration occurs, but not enough rights to work with data streams). Correction of this deficiency was performed in 2017. I attach a link to the error https://github.com/libusb/hidapi/commit/f7ee9ccd4e9978e996641795c09c4ed53a6f76c9#diff-8162c58f4630fb0f3a6a21f2e094e883
Please update the source code of the library to the current one, otherwise the package is not functional in Windows 10.

**Comment by prusnak** [comment]
Are you building the package from master? Very old sources indicate the issue you are not building the correct version of the package.

**Comment by AlexTochka** [comment]
pip install hidapi
I am doing this on Windows 10 on Python 3.8 from the WinPiton distribution.
