### ISSUE TITLE
Segfault on OS X

### ISSUE THREAD

**Issue by pepijndevos** [trezor/cython-hidapi#8]
I just did a pip install, so I have version `0.7.99-5`, running on Python 3.4.

```
$ python3
Python 3.4.2 (default, Oct 30 2014, 14:56:46) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hid
>>> dev = hid.device(5824, 1158)
>>> dev.read(64)
Segmentation fault: 11
```

**Comment by prusnak** [comment]
Read https://github.com/trezor/cython-hidapi/blob/master/try.py

You are using library incorrectly. Correct way is:
```
>>> import hid
>>> dev = hid.device()
>>> dev.open(5824, 1158)
>>> dev.read(64)
```

**Comment by pepijndevos** [comment]
Oh derp. Would it make sense to add a null check for groggy people like me? Anyway, thanks, I'll give it another go.

**Comment by prusnak** [comment]
This is a hidapi issue, not cython-hidapi. But feel free to create a pull request.

**Comment by pepijndevos** [comment]
Not really related to this issue, but while I have a communication channel open, I have two entries for the same vendor and product. One is my raw HID device, the other is the emulated serial from the Teensy. Your suggested code just picks one at random it seems. The way to tell them apart is by the usage field. https://forum.pjrc.com/archive/index.php/t-6838.html

**Comment by prusnak** [comment]
Better way is to enumerate devices using `enumerate` method and then open the one you want using `open_path` method.

**Comment by pepijndevos** [comment]
The path is *also* the same. But HIDAPI has the same limitation: https://github.com/signal11/hidapi/issues/193 So I'm fucked until that patch gets merged, or I build this project from source with the patch applied.

**Comment by prusnak** [comment]
That's really stupid. Blame crappy OS X USB stack ... :-/
