### ISSUE TITLE
Missing 0.9.0.post1 wheels for Windows

### ISSUE THREAD

**Issue by jonasmalacofilho** [trezor/cython-hidapi#80]
One of my CI builds for Windows picked up the latest version and wasn't able to built it with a non-obvious error.  While I'm still not sure what's causing the problem, I noticed that building cython-hidapi had never been necessary before, because wheels were used.

Wheels for Windows were released for `0.9.0` (earlier the same day)... can you do the same for `0.9.0.post1`?

**Comment by prusnak** [comment]
I can't because appveyor is failing.

**Comment by jonasmalacofilho** [comment]
Sure, I'll take a look.

**Comment by prusnak** [comment]
Fixed and uploaded 0.9.0.post2 to PyPI: https://pypi.org/project/hidapi/0.9.0.post2/#files

**Comment by jonasmalacofilho** [comment]
Thank you!
