### ISSUE TITLE
Calling hid_exit() in device.close() causes problems with multiple devices

### ISSUE THREAD

**Issue by jgilles** [trezor/cython-hidapi#84]
Using libusb backend, if multiple device connections are open simultaneously and close() is called on one device, this calls hid_exit() which then breaks all communication with any other devices that are still open.

hid_exit() calls libusb_exit() which can only be called at the end of an application when all use of the library is finished.

**Comment by prusnak** [comment]
Fixed in 1c96745f745d6ec79d584107b241c7f00d1d743d

Which is a revert of a commit added in https://github.com/trezor/cython-hidapi/pull/53

**Comment by jgilles** [comment]
Works, thanks!
