### ISSUE TITLE
Python 3 returns invalid path

### ISSUE THREAD

**Issue by lights0123** [trezor/cython-hidapi#86]
As mentioned in #38, the correct way to handle multiple devices is to use `enumerate` and then `open_path`. This works with Python 2; however, Python 3 fails when opening a `hidraw` path. I assume this is because Python 2 is using libusb and Python 3 is using hidraw, but I don't know how to configure that when installing via `pip`.

```py
❱ pip3 show hidapi             
Name: hidapi
Version: 0.9.0.post2
❱ python3
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hid
>>> hid.enumerate(0x16c0, 0x05df)
[{'path': b'/dev/hidraw0', 'vendor_id': 5824, 'product_id': 1503, 'serial_number': '', 'release_number': 256, 'manufacturer_string': 'www.dcttech.com', 'product_string': 'USBRelay8', 'usage_page': 0, 'usage': 0, 'interface_number': 0}]
>>> d = hid.device()
>>> d.open_path(b'/dev/hidraw0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hidraw.pyx", line 72, in hid.device.open_path
OSError: open failed

❱ pip2 show hidapi
Name: hidapi
Version: 0.9.0.post2
❱ python2
Python 2.7.18 (default, Apr 23 2020, 22:32:06) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hid
>>> hid.enumerate(0x16c0, 0x05df)
[{'usage_page': 0, 'interface_number': 0, 'product_id': 1503, 'serial_number': '', 'usage': 0, 'path': '0001:0040:00', 'manufacturer_string': u'www.dcttech.com', 'vendor_id': 5824, 'product_string': u'USBRelay8', 'release_number': 256}]
>>> d = hid.device()
>>> d.open_path('0001:0041:00')
>>>
```

**Comment by jonasmalacofilho** [comment]
You may simply be missing a udev rule that grants your unprivileged user access to the `/dev/hidraw0` device.

**Comment by Lindenk** [comment]
I'm having the same issue. `hidapi` incorrectly returns sys paths such as `0001:0041:00` instead of the actual filesystem device paths such as `/dev/hidraw0`. `open_path` expects the path returned by `hid.enumerate` but not a filesystem device path.

**Comment by prusnak** [comment]
> I'm having the same issue.

Does it work if you run it with root privileges? If yes, then you are missing udev rules for your device.

**Comment by Lindenk** [comment]
No it's not a permission issue. I can interact with the device just fine using the incorrect path `hid.enumerate` returns, and this happens regardless of permissions on the device or user running it.

**Comment by jonasmalacofilho** [comment]
@Lindenk 

> I'm having the same issue.
> I can interact with the device just fine

The statements above are clearly conflicting...

In fact, there's is nothing wrong with `enumerate()` returning a path like `0001:0041:00`, it's just that the backend in use is libusb, not hidraw.  And as long as `open_path()` is also taken from the same backend (here equal to module), it will work just fine.

```
$ python -m venv venv
$ source venv/bin/activate
$ pip install hidapi

# hid (libusb based under default settings) works fine
$ python -c "import hid; hid.device().open_path(hid.enumerate()[0]['path'])"

# hidraw also works fine
$ python -c "import hidraw; hidraw.device().open_path(hidraw.enumerate()[0]['path'])"

# but don't use libusb paths with hidraw
$ python -c "import hid; import hidraw; hid.device().open_path(hidraw.enumerate()[0]['path'])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "hid.pyx", line 74, in hid.device.open_path
OSError: open failed
```
