### ISSUE TITLE
Support for the "get_input_report" hidapi function

### ISSUE THREAD

**Issue by K-Visscher** [trezor/cython-hidapi#87]
Hello,

As an enhancement to this library (which is great btw), would it be possible to add a binding  for the [`get_input_report`](https://github.com/libusb/hidapi/blob/d38dbd2e99b088e029933dfd64c1294e000e5bcc/hidapi/hidapi.h#L360) function?

This would really suite my use case, and is nice to have in general (imho).

Kind regards,
Kim

**Comment by prusnak** [comment]
Can you try to create and submit a pull request?

**Comment by K-Visscher** [comment]
@prusnak Thanks for your quick reply, yes sure, I'll create a fork and work on it! 
It might take some time though since I'm in the process of graduating

**Comment by K-Visscher** [comment]
@prusnak Could you maybe make a release for this on PyPi? Thanks!

**Comment by prusnak** [comment]
Released 0.9.0.post3 to PyPI. Thanks! https://pypi.org/project/hidapi/
