### ISSUE TITLE
make libusb optional on linux

### ISSUE THREAD

**Issue by vlotorev** [trezor/cython-hidapi#9]
Hello,

my suggestion is to make libusb optional (hidraw provides the same functionality, right?)

I can provide pull request for this feature, but like to get approval and discuss implementation details.

Some python packages provide optional features while installing (a list of packages can be extracted from [1]). It's common practice to add --with-feature or --without-feature options for 'python setup.py install' command.

I suggest adding '--without-libusb' for linux that would disable libusb as hard requirement and build only hidraw module.

The exact implementation of parsing '--without..' can be taken from setup.py of pylibmc package [2].

[1] -- https://github.com/pypa/pip/issues/271
[2] -- https://github.com/lericson/pylibmc/blob/master/setup.py

**Comment by prusnak** [comment]
What is the motivation? Is there a Linux system where libusb is not present?

**Comment by vlotorev** [comment]
I'm targeting at embedded platform, so adding userspace library (libusb) for the same that's already done by kernel looks like extra needless dependency.

Actually as far as I understand libusb had existed long before hidraw appeared in 2007. So using libusb while developing hidapi library for raw hid access was the only choice (this situation is also noted in commit message of the very first commit of hidraw [1]). But once hidraw appeared in kernel support for it was added into hidapi library.

So, IMHO, generally libusb should be used only as a last resort when kernel is built without hidraw support.

[1] -- http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=86166b7bcda0bcb53525114fa1c87ac432be478e

**Comment by prusnak** [comment]
Could you prepare a pullrequest implementing --without-libusb switch?
