### ISSUE TITLE
missing hid_exit()

### ISSUE THREAD

**Issue by wjasper** [trezor/cython-hidapi#91]
In the original hidapi, there is a C function hid_exit().  I noticed that you only have hid.close().  Is there a reason
that there is no python wrapper for hid_exit()?  I have written a driver for a usb-3103 by Measurement Computing.  It works great in C/C++ using hidapi.  When I converted over to python, the driver also
works, but on exit, I need to reset the device since things are not closing correctly at a much lower level.  I think
having the function hid_exit() would fix my problems.
Thanks,
Warren

**Comment by RobertoRoos** [comment]
This should be fixed by the mentioned PR, but I can't test if it solves a problem because I don't get that problem.

**Comment by prusnak** [comment]
Fixed via https://github.com/trezor/cython-hidapi/pull/111 - commit b94c8a0
