### ISSUE TITLE
Missing `__x86_64__` in CFLAGS for Darwin (Unsupported architecture / architecture not supported)

### ISSUE THREAD

**Issue by canselcik** [trezor/cython-hidapi#96]
This causes build to fail on OSX with:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/machine/limits.h:8:2: error:
      architecture not supported
#error architecture not supported
```

Addressed by the following change:
```diff
 if sys.platform.startswith('darwin'):
     macos_sdk_path = subprocess.check_output(['xcrun', '--show-sdk-path']).decode().strip()
-     os.environ['CFLAGS'] = '-isysroot "%s" -framework IOKit -framework CoreFoundation' % macos_sdk_path
+     os.environ['CFLAGS'] = ' -D__x86_64__ -isysroot "%s" -framework IOKit -framework CoreFoundation' % macos_sdk_path
```

**Comment by prusnak** [comment]
I don't like this fix. Especially with the upcoming macOS for arm64 arch. I think this should be fixed in hidapi upstream by including the correct include file. Can you please create an issue here - https://github.com/libusb/hidapi/issues, including the whole build failure log (not just the error, but more context)? Thanks!

**Comment by canselcik** [comment]
Will do @prusnak, thanks.

**Comment by Sup3rGeo** [comment]
Just in case someone wants to have something installable in the meantime, I created a fork with the fix that can be installed by running `pip install git+https://github.com/Sup3rGeo/cython-hidapi`

**Comment by prusnak** [comment]
@canselcik did you send the issue to upstream?

**Comment by prusnak** [comment]
@canselcik What does `xcrun --show-sdk-version` say?

I am on SDK 11.1 + Apple Silicon and `python3 setup.py build` properly generates `build/lib.macosx-10.14.6-arm64-3.8/hid.cpython-38-darwin.so` which is universal binary for both x86_64 and arm64:

```
$ file build/lib.macosx-10.14.6-arm64-3.8/hid.cpython-38-darwin.so
build/lib.macosx-10.14.6-arm64-3.8/hid.cpython-38-darwin.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64:Mach-O 64-bit bundle arm64]
build/lib.macosx-10.14.6-arm64-3.8/hid.cpython-38-darwin.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
build/lib.macosx-10.14.6-arm64-3.8/hid.cpython-38-darwin.so (for architecture arm64):	Mach-O 64-bit bundle arm64
```

I am hesitant to hardcode the x86_64 architecture as this really seems to be an issue with that particular version of the SDK you have.

**Comment by Sup3rGeo** [comment]
In my case I have `10.15.6`. Does it mean the solution is to update the SDK? Any pointers how to do it?

**Comment by prusnak** [comment]
> In my case I have `10.15.6`. Does it mean the solution is to update the SDK? Any pointers how to do it?

Install the latest Xcode from the App Store. If you are on the latest Xcode from the App Store, I assume you need to update your system to latest macOS version (Big Sur).

**Comment by prusnak** [comment]
I added wheel builder action added in https://github.com/trezor/cython-hidapi/commit/b16f093b47edaaf1362d2fdcc3584d8633431342

and resulting wheels uploaded to PyPI: https://pypi.org/project/hidapi/#files

@Sup3rGeo @canselcik Hopefully pip3 install will fetch the wheels for you and you won't need to build them from source.
