### ISSUE TITLE
Release wheels for macOS and Linux

### ISSUE THREAD

**Issue by flit** [trezor/cython-hidapi#99]
The project is already using CI, so building wheels is not too far a step.

**Comment by prusnak** [comment]
Wheels have been always available, see e.g. https://pypi.org/project/hidapi/0.10.1/#files

**Comment by flit** [comment]
Ok, but the wheel are Windows-only. This issue specifically called out "common platforms", not just Windows. So I'd appreciate if you could reopen it. I'll change the title to more explicitly state macOS and Linux. AArch64 wheels would be useful too.

**Comment by prusnak** [comment]
Pull requests are welcome, I have no capacity to work on this.

**Comment by flit** [comment]
That's fine and totally understandable, but it should be tracked.

**Comment by flit** [comment]
Thanks! 👍

**Comment by prusnak** [comment]
Wheel builder action added in https://github.com/trezor/cython-hidapi/commit/b16f093b47edaaf1362d2fdcc3584d8633431342

And resulting wheels uploaded to PyPI: https://pypi.org/project/hidapi/#files
